language: node_js
node_js:
- '6'
sudo: false
cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_install:
  - rvm install 2.2.2

script:
 - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run build; fi'

after_success:
- staticland login -e $user -p $key
- npm run deploy
