language: node_js
node_js:
- '6'
sudo: false
cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_install:
  - rvm install 2.2.2

install:
  - npm install

script:
 - 'npm run build'

after_success:
  - 'echo $wut'
  - 'staticland login -e $email -p $key'
  - 'npm run deploy'
