language: node_js
node_js:
- '6'
sudo: false
cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_install:
  - rvm install 2.2.2

install:
  - npm install

script:
 - '$TRAVIS_PULL_REQUEST == "false" && npm run build'

after_success:
- '$TRAVIS_PULL_REQUEST == "false" && staticland login -e $user -p $key'
- '$TRAVIS_PULL_REQUEST == "false" && npm run deploy'
