language: node_js
node_js:
- '6'
sudo: false
cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_install:
  - rvm install 2.2.2

install:
  - npm install

script:
 - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then npm run build; fi'

after_success:
- 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then staticland login -e $user -p $key; fi'
- 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; npm run deploy; fi'
